using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("SDL DXA Public Content API")]

// NOTE: Common Assembly Info is generated by the build in CommonAssemblyInfo.cs
