// Java This file was generated by a tool on 7/19/2018 3:49:57 PM
package com.sdl.web;
import java.util.List;
import java.util.Dictionary;
	/// <summary>
	/// The query root for the GraphQL Public Content API.
	/// </summary>
	class ContentQuery
	{
		private BinaryComponent binaryComponent;   
		private KeywordConnection categories;   
		private ComponentPresentation componentPresentation;   
		private ItemConnection items;   
		private Keyword keyword;   
		private Page page;   
		private PageConnection pages;   
		private Publication publication;   
		private PublicationConnection publications;   
		private StructureGroup structureGroup;   
		private StructureGroupConnection structureGroups;   
		private TaxonomySitemapItem sitemap;   
		private TaxonomySitemapItem sitemapSubtree;   

		 public BinaryComponent getBinaryComponent()
		 {
			 return binaryComponent;
		 }
		 public void setBinaryComponent(BinaryComponent binaryComponent)
		 {
			 this.binaryComponent = binaryComponent;
		 }

		 public KeywordConnection getCategories()
		 {
			 return categories;
		 }
		 public void setCategories(KeywordConnection categories)
		 {
			 this.categories = categories;
		 }

		 public ComponentPresentation getComponentPresentation()
		 {
			 return componentPresentation;
		 }
		 public void setComponentPresentation(ComponentPresentation componentPresentation)
		 {
			 this.componentPresentation = componentPresentation;
		 }

		 public ItemConnection getItems()
		 {
			 return items;
		 }
		 public void setItems(ItemConnection items)
		 {
			 this.items = items;
		 }

		 public Keyword getKeyword()
		 {
			 return keyword;
		 }
		 public void setKeyword(Keyword keyword)
		 {
			 this.keyword = keyword;
		 }

		 public Page getPage()
		 {
			 return page;
		 }
		 public void setPage(Page page)
		 {
			 this.page = page;
		 }

		 public PageConnection getPages()
		 {
			 return pages;
		 }
		 public void setPages(PageConnection pages)
		 {
			 this.pages = pages;
		 }

		 public Publication getPublication()
		 {
			 return publication;
		 }
		 public void setPublication(Publication publication)
		 {
			 this.publication = publication;
		 }

		 public PublicationConnection getPublications()
		 {
			 return publications;
		 }
		 public void setPublications(PublicationConnection publications)
		 {
			 this.publications = publications;
		 }

		 public StructureGroup getStructureGroup()
		 {
			 return structureGroup;
		 }
		 public void setStructureGroup(StructureGroup structureGroup)
		 {
			 this.structureGroup = structureGroup;
		 }

		 public StructureGroupConnection getStructureGroups()
		 {
			 return structureGroups;
		 }
		 public void setStructureGroups(StructureGroupConnection structureGroups)
		 {
			 this.structureGroups = structureGroups;
		 }

		 public TaxonomySitemapItem getSitemap()
		 {
			 return sitemap;
		 }
		 public void setSitemap(TaxonomySitemapItem sitemap)
		 {
			 this.sitemap = sitemap;
		 }

		 public TaxonomySitemapItem getSitemapSubtree()
		 {
			 return sitemapSubtree;
		 }
		 public void setSitemapSubtree(TaxonomySitemapItem sitemapSubtree)
		 {
			 this.sitemapSubtree = sitemapSubtree;
		 }
	}

	/// <summary>
	/// Represents a component which has binary content.
	/// </summary>
	class BinaryComponent implements IItem
	{
		private String creationDate;   
		private CustomMetaConnection customMetas;   
		private String id;   
		private String initialPublishDate;   
		private int itemId;   
		private int itemType;   
		private String lastPublishDate;   
		private int namespaceId;   
		private int owningPublicationId;   
		private int publicationId;   
		private int schemaId;   
		private List<ITaxonomyItem> taxonomies;   
		private String title;   
		private String type;   
		private String updatedDate;   
		private BinaryVariantConnection variants;   
		private boolean multiMedia;   

		 public String getCreationDate()
		 {
			 return creationDate;
		 }
		 public void setCreationDate(String creationDate)
		 {
			 this.creationDate = creationDate;
		 }

		 public CustomMetaConnection getCustomMetas()
		 {
			 return customMetas;
		 }
		 public void setCustomMetas(CustomMetaConnection customMetas)
		 {
			 this.customMetas = customMetas;
		 }

		 public String getId()
		 {
			 return id;
		 }
		 public void setId(String id)
		 {
			 this.id = id;
		 }

		 public String getInitialPublishDate()
		 {
			 return initialPublishDate;
		 }
		 public void setInitialPublishDate(String initialPublishDate)
		 {
			 this.initialPublishDate = initialPublishDate;
		 }

		 public int getItemId()
		 {
			 return itemId;
		 }
		 public void setItemId(int itemId)
		 {
			 this.itemId = itemId;
		 }

		 public int getItemType()
		 {
			 return itemType;
		 }
		 public void setItemType(int itemType)
		 {
			 this.itemType = itemType;
		 }

		 public String getLastPublishDate()
		 {
			 return lastPublishDate;
		 }
		 public void setLastPublishDate(String lastPublishDate)
		 {
			 this.lastPublishDate = lastPublishDate;
		 }

		 public int getNamespaceId()
		 {
			 return namespaceId;
		 }
		 public void setNamespaceId(int namespaceId)
		 {
			 this.namespaceId = namespaceId;
		 }

		 public int getOwningPublicationId()
		 {
			 return owningPublicationId;
		 }
		 public void setOwningPublicationId(int owningPublicationId)
		 {
			 this.owningPublicationId = owningPublicationId;
		 }

		 public int getPublicationId()
		 {
			 return publicationId;
		 }
		 public void setPublicationId(int publicationId)
		 {
			 this.publicationId = publicationId;
		 }

		 public int getSchemaId()
		 {
			 return schemaId;
		 }
		 public void setSchemaId(int schemaId)
		 {
			 this.schemaId = schemaId;
		 }

		 public List<ITaxonomyItem> getTaxonomies()
		 {
			 return taxonomies;
		 }
		 public void setTaxonomies(List<ITaxonomyItem> taxonomies)
		 {
			 this.taxonomies = taxonomies;
		 }

		 public String getTitle()
		 {
			 return title;
		 }
		 public void setTitle(String title)
		 {
			 this.title = title;
		 }

		 public String getType()
		 {
			 return type;
		 }
		 public void setType(String type)
		 {
			 this.type = type;
		 }

		 public String getUpdatedDate()
		 {
			 return updatedDate;
		 }
		 public void setUpdatedDate(String updatedDate)
		 {
			 this.updatedDate = updatedDate;
		 }

		 public BinaryVariantConnection getVariants()
		 {
			 return variants;
		 }
		 public void setVariants(BinaryVariantConnection variants)
		 {
			 this.variants = variants;
		 }

		 public boolean isMultiMedia()
		 {
			 return multiMedia;
		 }
		 public void setMultiMedia(boolean multiMedia)
		 {
			 this.multiMedia = multiMedia;
		 }
	}

	/// <summary>
	/// A connection to a list of items.
	/// </summary>
	class CustomMetaConnection
	{
		private List<CustomMetaEdge> edges;   

		 public List<CustomMetaEdge> getEdges()
		 {
			 return edges;
		 }
		 public void setEdges(List<CustomMetaEdge> edges)
		 {
			 this.edges = edges;
		 }
	}

	/// <summary>
	/// An edge in a connection
	/// </summary>
	class CustomMetaEdge
	{
		private CustomMeta node;   
		private String cursor;   

		 public CustomMeta getNode()
		 {
			 return node;
		 }
		 public void setNode(CustomMeta node)
		 {
			 this.node = node;
		 }

		 public String getCursor()
		 {
			 return cursor;
		 }
		 public void setCursor(String cursor)
		 {
			 this.cursor = cursor;
		 }
	}

	/// <summary>
	/// Represents custom metadata.
	/// </summary>
	class CustomMeta
	{
		private String id;   
		private int itemId;   
		private String key;   
		private int namespaceId;   
		private int publicationId;   
		private String value;   
		private CustomMetaValueType valueType;   

		 public String getId()
		 {
			 return id;
		 }
		 public void setId(String id)
		 {
			 this.id = id;
		 }

		 public int getItemId()
		 {
			 return itemId;
		 }
		 public void setItemId(int itemId)
		 {
			 this.itemId = itemId;
		 }

		 public String getKey()
		 {
			 return key;
		 }
		 public void setKey(String key)
		 {
			 this.key = key;
		 }

		 public int getNamespaceId()
		 {
			 return namespaceId;
		 }
		 public void setNamespaceId(int namespaceId)
		 {
			 this.namespaceId = namespaceId;
		 }

		 public int getPublicationId()
		 {
			 return publicationId;
		 }
		 public void setPublicationId(int publicationId)
		 {
			 this.publicationId = publicationId;
		 }

		 public String getValue()
		 {
			 return value;
		 }
		 public void setValue(String value)
		 {
			 this.value = value;
		 }

		 public CustomMetaValueType getValueType()
		 {
			 return valueType;
		 }
		 public void setValueType(CustomMetaValueType valueType)
		 {
			 this.valueType = valueType;
		 }
	}

	/*[JsonConverter(typeof(StringEnumConverter))]*/
	enum CustomMetaValueType
	{
		/// <summary>
		/// STRING
		/// </summary>
		STRING,

		/// <summary>
		/// DATE
		/// </summary>
		DATE,

		/// <summary>
		/// FLOAT
		/// </summary>
		FLOAT,

		/// <summary>
		/// NUMBER
		/// </summary>
		NUMBER,

		UNKNOWN
	}

	/// <summary>
	/// Represents a taxonomy item.
	/// </summary>
	interface ITaxonomyItem
	{
		TaxonomyItemConnection children = null;  
		String creationDate = null;  
		CustomMetaConnection customMetas = null;  
		int depth = 0;  
		String id = null;  
		String initialPublishDate = null;  
		int itemId = 0;  
		int itemType = 0;  
		String key = null;  
		String lastPublishDate = null;  
		int namespaceId = 0;  
		int owningPublicationId = 0;  
		ITaxonomyItem parent = null;  
		int publicationId = 0;  
		int taxonomyId = 0;  
		TaxonomyType taxonomyType = null;  
		String title = null;  
		String updatedDate = null;  
		boolean hasChildren = false;  
		boolean Abstract = false;  
		boolean navigable = false;  


		TaxonomyItemConnection getChildren();
		void setChildren(TaxonomyItemConnection children);

		String getCreationDate();
		void setCreationDate(String creationDate);

		CustomMetaConnection getCustomMetas();
		void setCustomMetas(CustomMetaConnection customMetas);

		int getDepth();
		void setDepth(int depth);

		String getId();
		void setId(String id);

		String getInitialPublishDate();
		void setInitialPublishDate(String initialPublishDate);

		int getItemId();
		void setItemId(int itemId);

		int getItemType();
		void setItemType(int itemType);

		String getKey();
		void setKey(String key);

		String getLastPublishDate();
		void setLastPublishDate(String lastPublishDate);

		int getNamespaceId();
		void setNamespaceId(int namespaceId);

		int getOwningPublicationId();
		void setOwningPublicationId(int owningPublicationId);

		ITaxonomyItem getParent();
		void setParent(ITaxonomyItem parent);

		int getPublicationId();
		void setPublicationId(int publicationId);

		int getTaxonomyId();
		void setTaxonomyId(int taxonomyId);

		TaxonomyType getTaxonomyType();
		void setTaxonomyType(TaxonomyType taxonomyType);

		String getTitle();
		void setTitle(String title);

		String getUpdatedDate();
		void setUpdatedDate(String updatedDate);

		boolean isHasChildren();
		void setHasChildren(boolean hasChildren);

		boolean isAbstract();
		void setAbstract(boolean anAbstract);

		boolean isNavigable();
		void setNavigable(boolean navigable);
	}

	/// <summary>
	/// A connection to a list of items.
	/// </summary>
	class TaxonomyItemConnection
	{
		private List<TaxonomyItemEdge> edges;   

		 public List<TaxonomyItemEdge> getEdges()
		 {
			 return edges;
		 }
		 public void setEdges(List<TaxonomyItemEdge> edges)
		 {
			 this.edges = edges;
		 }
	}

	/// <summary>
	/// An edge in a connection
	/// </summary>
	class TaxonomyItemEdge
	{
		private ITaxonomyItem node;   
		private String cursor;   

		 public ITaxonomyItem getNode()
		 {
			 return node;
		 }
		 public void setNode(ITaxonomyItem node)
		 {
			 this.node = node;
		 }

		 public String getCursor()
		 {
			 return cursor;
		 }
		 public void setCursor(String cursor)
		 {
			 this.cursor = cursor;
		 }
	}

	/*[JsonConverter(typeof(StringEnumConverter))]*/
	enum TaxonomyType
	{
		/// <summary>
		/// KEYWORD
		/// </summary>
		KEYWORD,

		/// <summary>
		/// CATEGORY
		/// </summary>
		CATEGORY,

		STRUCTUREGROUP
	}

	/// <summary>
	/// A connection to a list of items.
	/// </summary>
	class BinaryVariantConnection
	{
		private List<BinaryVariantEdge> edges;   

		 public List<BinaryVariantEdge> getEdges()
		 {
			 return edges;
		 }
		 public void setEdges(List<BinaryVariantEdge> edges)
		 {
			 this.edges = edges;
		 }
	}

	/// <summary>
	/// An edge in a connection
	/// </summary>
	class BinaryVariantEdge
	{
		private BinaryVariant node;   
		private String cursor;   

		 public BinaryVariant getNode()
		 {
			 return node;
		 }
		 public void setNode(BinaryVariant node)
		 {
			 this.node = node;
		 }

		 public String getCursor()
		 {
			 return cursor;
		 }
		 public void setCursor(String cursor)
		 {
			 this.cursor = cursor;
		 }
	}

	/// <summary>
	/// Represents a variant of a binary component.
	/// </summary>
	class BinaryVariant
	{
		private int binaryId;   
		private String description;   
		private String downloadUrl;   
		private String id;   
		private String path;   
		private String type;   
		private String url;   
		private String variantId;   

		 public int getBinaryId()
		 {
			 return binaryId;
		 }
		 public void setBinaryId(int binaryId)
		 {
			 this.binaryId = binaryId;
		 }

		 public String getDescription()
		 {
			 return description;
		 }
		 public void setDescription(String description)
		 {
			 this.description = description;
		 }

		 public String getDownloadUrl()
		 {
			 return downloadUrl;
		 }
		 public void setDownloadUrl(String downloadUrl)
		 {
			 this.downloadUrl = downloadUrl;
		 }

		 public String getId()
		 {
			 return id;
		 }
		 public void setId(String id)
		 {
			 this.id = id;
		 }

		 public String getPath()
		 {
			 return path;
		 }
		 public void setPath(String path)
		 {
			 this.path = path;
		 }

		 public String getType()
		 {
			 return type;
		 }
		 public void setType(String type)
		 {
			 this.type = type;
		 }

		 public String getUrl()
		 {
			 return url;
		 }
		 public void setUrl(String url)
		 {
			 this.url = url;
		 }

		 public String getVariantId()
		 {
			 return variantId;
		 }
		 public void setVariantId(String variantId)
		 {
			 this.variantId = variantId;
		 }
	}

	/// <summary>
	/// Represents a component which has content.
	/// </summary>
	interface IContentComponent
	{
		String creationDate = null;  
		CustomMetaConnection customMetas = null;  
		String id = null;  
		String initialPublishDate = null;  
		int itemId = 0;  
		int itemType = 0;  
		String lastPublishDate = null;  
		int namespaceId = 0;  
		int owningPublicationId = 0;  
		int publicationId = 0;  
		int schemaId = 0;  
		List<ITaxonomyItem> taxonomies = null;  
		String title = null;  
		String updatedDate = null;  
		boolean multiMedia = false;  


		String getCreationDate();
		void setCreationDate(String creationDate);

		CustomMetaConnection getCustomMetas();
		void setCustomMetas(CustomMetaConnection customMetas);

		String getId();
		void setId(String id);

		String getInitialPublishDate();
		void setInitialPublishDate(String initialPublishDate);

		int getItemId();
		void setItemId(int itemId);

		int getItemType();
		void setItemType(int itemType);

		String getLastPublishDate();
		void setLastPublishDate(String lastPublishDate);

		int getNamespaceId();
		void setNamespaceId(int namespaceId);

		int getOwningPublicationId();
		void setOwningPublicationId(int owningPublicationId);

		int getPublicationId();
		void setPublicationId(int publicationId);

		int getSchemaId();
		void setSchemaId(int schemaId);

		List<ITaxonomyItem> getTaxonomies();
		void setTaxonomies(List<ITaxonomyItem> taxonomies);

		String getTitle();
		void setTitle(String title);

		String getUpdatedDate();
		void setUpdatedDate(String updatedDate);

		boolean isMultiMedia();
		void setMultiMedia(boolean multiMedia);
	}

	/// <summary>
	/// Represents an item. The root of all content models.
	/// </summary>
	interface IItem
	{
		String creationDate = null;  
		CustomMetaConnection customMetas = null;  
		String id = null;  
		String initialPublishDate = null;  
		int itemId = 0;  
		int itemType = 0;  
		String lastPublishDate = null;  
		int namespaceId = 0;  
		int owningPublicationId = 0;  
		int publicationId = 0;  
		String title = null;  
		String updatedDate = null;  


		String getCreationDate();
		void setCreationDate(String creationDate);

		CustomMetaConnection getCustomMetas();
		void setCustomMetas(CustomMetaConnection customMetas);

		String getId();
		void setId(String id);

		String getInitialPublishDate();
		void setInitialPublishDate(String initialPublishDate);

		int getItemId();
		void setItemId(int itemId);

		int getItemType();
		void setItemType(int itemType);

		String getLastPublishDate();
		void setLastPublishDate(String lastPublishDate);

		int getNamespaceId();
		void setNamespaceId(int namespaceId);

		int getOwningPublicationId();
		void setOwningPublicationId(int owningPublicationId);

		int getPublicationId();
		void setPublicationId(int publicationId);

		String getTitle();
		void setTitle(String title);

		String getUpdatedDate();
		void setUpdatedDate(String updatedDate);
	}

	/// <summary>
	/// Represents an Ambient Data Framework claim value.
	/// </summary>
	class InputClaimValue
	{
		private ClaimValueType type;   
		private String uri;   
		private String value;   

		 public ClaimValueType getType()
		 {
			 return type;
		 }
		 public void setType(ClaimValueType type)
		 {
			 this.type = type;
		 }

		 public String getUri()
		 {
			 return uri;
		 }
		 public void setUri(String uri)
		 {
			 this.uri = uri;
		 }

		 public String getValue()
		 {
			 return value;
		 }
		 public void setValue(String value)
		 {
			 this.value = value;
		 }
	}

	/// <summary>
	/// Represents the type of claim value.
	/// </summary>
	/*[JsonConverter(typeof(StringEnumConverter))]*/
	enum ClaimValueType
	{
		/// <summary>
		/// A string value.
		/// </summary>
		STRING,

		/// <summary>
		/// A date value.
		/// </summary>
		DATE,

		/// <summary>
		/// A float value.
		/// </summary>
		FLOAT,

		/// <summary>
		/// A number value.
		/// </summary>
		NUMBER,

		BOOLEAN
	}

	/// <summary>
	/// A connection to a list of items.
	/// </summary>
	class KeywordConnection
	{
		private List<KeywordEdge> edges;   

		 public List<KeywordEdge> getEdges()
		 {
			 return edges;
		 }
		 public void setEdges(List<KeywordEdge> edges)
		 {
			 this.edges = edges;
		 }
	}

	/// <summary>
	/// An edge in a connection
	/// </summary>
	class KeywordEdge
	{
		private Keyword node;   
		private String cursor;   

		 public Keyword getNode()
		 {
			 return node;
		 }
		 public void setNode(Keyword node)
		 {
			 this.node = node;
		 }

		 public String getCursor()
		 {
			 return cursor;
		 }
		 public void setCursor(String cursor)
		 {
			 this.cursor = cursor;
		 }
	}

	/// <summary>
	/// Represents a keyword taxonomy item.
	/// </summary>
	class Keyword implements IItem
	{
		private TaxonomyItemConnection children;   
		private String creationDate;   
		private CustomMetaConnection customMetas;   
		private int depth;   
		private String description;   
		private String id;   
		private String initialPublishDate;   
		private int itemId;   
		private int itemType;   
		private String key;   
		private String lastPublishDate;   
		private String name;   
		private int namespaceId;   
		private int owningPublicationId;   
		private ITaxonomyItem parent;   
		private int publicationId;   
		private int taxonomyId;   
		private TaxonomyType taxonomyType;   
		private String title;   
		private int totalRelatedItems;   
		private String updatedDate;   
		private boolean hasChildren;   
		private boolean Abstract;   
		private boolean navigable;   
		private boolean usedForIdentification;   

		 public TaxonomyItemConnection getChildren()
		 {
			 return children;
		 }
		 public void setChildren(TaxonomyItemConnection children)
		 {
			 this.children = children;
		 }

		 public String getCreationDate()
		 {
			 return creationDate;
		 }
		 public void setCreationDate(String creationDate)
		 {
			 this.creationDate = creationDate;
		 }

		 public CustomMetaConnection getCustomMetas()
		 {
			 return customMetas;
		 }
		 public void setCustomMetas(CustomMetaConnection customMetas)
		 {
			 this.customMetas = customMetas;
		 }

		 public int getDepth()
		 {
			 return depth;
		 }
		 public void setDepth(int depth)
		 {
			 this.depth = depth;
		 }

		 public String getDescription()
		 {
			 return description;
		 }
		 public void setDescription(String description)
		 {
			 this.description = description;
		 }

		 public String getId()
		 {
			 return id;
		 }
		 public void setId(String id)
		 {
			 this.id = id;
		 }

		 public String getInitialPublishDate()
		 {
			 return initialPublishDate;
		 }
		 public void setInitialPublishDate(String initialPublishDate)
		 {
			 this.initialPublishDate = initialPublishDate;
		 }

		 public int getItemId()
		 {
			 return itemId;
		 }
		 public void setItemId(int itemId)
		 {
			 this.itemId = itemId;
		 }

		 public int getItemType()
		 {
			 return itemType;
		 }
		 public void setItemType(int itemType)
		 {
			 this.itemType = itemType;
		 }

		 public String getKey()
		 {
			 return key;
		 }
		 public void setKey(String key)
		 {
			 this.key = key;
		 }

		 public String getLastPublishDate()
		 {
			 return lastPublishDate;
		 }
		 public void setLastPublishDate(String lastPublishDate)
		 {
			 this.lastPublishDate = lastPublishDate;
		 }

		 public String getName()
		 {
			 return name;
		 }
		 public void setName(String name)
		 {
			 this.name = name;
		 }

		 public int getNamespaceId()
		 {
			 return namespaceId;
		 }
		 public void setNamespaceId(int namespaceId)
		 {
			 this.namespaceId = namespaceId;
		 }

		 public int getOwningPublicationId()
		 {
			 return owningPublicationId;
		 }
		 public void setOwningPublicationId(int owningPublicationId)
		 {
			 this.owningPublicationId = owningPublicationId;
		 }

		 public ITaxonomyItem getParent()
		 {
			 return parent;
		 }
		 public void setParent(ITaxonomyItem parent)
		 {
			 this.parent = parent;
		 }

		 public int getPublicationId()
		 {
			 return publicationId;
		 }
		 public void setPublicationId(int publicationId)
		 {
			 this.publicationId = publicationId;
		 }

		 public int getTaxonomyId()
		 {
			 return taxonomyId;
		 }
		 public void setTaxonomyId(int taxonomyId)
		 {
			 this.taxonomyId = taxonomyId;
		 }

		 public TaxonomyType getTaxonomyType()
		 {
			 return taxonomyType;
		 }
		 public void setTaxonomyType(TaxonomyType taxonomyType)
		 {
			 this.taxonomyType = taxonomyType;
		 }

		 public String getTitle()
		 {
			 return title;
		 }
		 public void setTitle(String title)
		 {
			 this.title = title;
		 }

		 public int getTotalRelatedItems()
		 {
			 return totalRelatedItems;
		 }
		 public void setTotalRelatedItems(int totalRelatedItems)
		 {
			 this.totalRelatedItems = totalRelatedItems;
		 }

		 public String getUpdatedDate()
		 {
			 return updatedDate;
		 }
		 public void setUpdatedDate(String updatedDate)
		 {
			 this.updatedDate = updatedDate;
		 }

		 public boolean isHasChildren()
		 {
			 return hasChildren;
		 }
		 public void setHasChildren(boolean hasChildren)
		 {
			 this.hasChildren = hasChildren;
		 }

		 public boolean isAbstract()
		 {
			 return Abstract;
		 }
		 public void setAbstract(boolean anAbstract)
		 {
			 this.Abstract = anAbstract;
		 }

		 public boolean isNavigable()
		 {
			 return navigable;
		 }
		 public void setNavigable(boolean navigable)
		 {
			 this.navigable = navigable;
		 }

		 public boolean isUsedForIdentification()
		 {
			 return usedForIdentification;
		 }
		 public void setUsedForIdentification(boolean usedForIdentification)
		 {
			 this.usedForIdentification = usedForIdentification;
		 }
	}

	/// <summary>
	/// Represents a component presentation which has a component associated with a template.
	/// </summary>
	class ComponentPresentation implements IItem
	{
		private IContentComponent component;   
		private Template componentTemplate;   
		private IContent content;   
		private String creationDate;   
		private CustomMetaConnection customMetas;   
		private String id;   
		private String initialPublishDate;   
		private int itemId;   
		private int itemType;   
		private String lastPublishDate;   
		private int namespaceId;   
		private int owningPublicationId;   
		private int publicationId;   
		private RawContent rawContent;   
		private String title;   
		private String updatedDate;   

		 public IContentComponent getComponent()
		 {
			 return component;
		 }
		 public void setComponent(IContentComponent component)
		 {
			 this.component = component;
		 }

		 public Template getComponentTemplate()
		 {
			 return componentTemplate;
		 }
		 public void setComponentTemplate(Template componentTemplate)
		 {
			 this.componentTemplate = componentTemplate;
		 }

		 public IContent getContent()
		 {
			 return content;
		 }
		 public void setContent(IContent content)
		 {
			 this.content = content;
		 }

		 public String getCreationDate()
		 {
			 return creationDate;
		 }
		 public void setCreationDate(String creationDate)
		 {
			 this.creationDate = creationDate;
		 }

		 public CustomMetaConnection getCustomMetas()
		 {
			 return customMetas;
		 }
		 public void setCustomMetas(CustomMetaConnection customMetas)
		 {
			 this.customMetas = customMetas;
		 }

		 public String getId()
		 {
			 return id;
		 }
		 public void setId(String id)
		 {
			 this.id = id;
		 }

		 public String getInitialPublishDate()
		 {
			 return initialPublishDate;
		 }
		 public void setInitialPublishDate(String initialPublishDate)
		 {
			 this.initialPublishDate = initialPublishDate;
		 }

		 public int getItemId()
		 {
			 return itemId;
		 }
		 public void setItemId(int itemId)
		 {
			 this.itemId = itemId;
		 }

		 public int getItemType()
		 {
			 return itemType;
		 }
		 public void setItemType(int itemType)
		 {
			 this.itemType = itemType;
		 }

		 public String getLastPublishDate()
		 {
			 return lastPublishDate;
		 }
		 public void setLastPublishDate(String lastPublishDate)
		 {
			 this.lastPublishDate = lastPublishDate;
		 }

		 public int getNamespaceId()
		 {
			 return namespaceId;
		 }
		 public void setNamespaceId(int namespaceId)
		 {
			 this.namespaceId = namespaceId;
		 }

		 public int getOwningPublicationId()
		 {
			 return owningPublicationId;
		 }
		 public void setOwningPublicationId(int owningPublicationId)
		 {
			 this.owningPublicationId = owningPublicationId;
		 }

		 public int getPublicationId()
		 {
			 return publicationId;
		 }
		 public void setPublicationId(int publicationId)
		 {
			 this.publicationId = publicationId;
		 }

		 public RawContent getRawContent()
		 {
			 return rawContent;
		 }
		 public void setRawContent(RawContent rawContent)
		 {
			 this.rawContent = rawContent;
		 }

		 public String getTitle()
		 {
			 return title;
		 }
		 public void setTitle(String title)
		 {
			 this.title = title;
		 }

		 public String getUpdatedDate()
		 {
			 return updatedDate;
		 }
		 public void setUpdatedDate(String updatedDate)
		 {
			 this.updatedDate = updatedDate;
		 }
	}

	/// <summary>
	/// Represents a template.
	/// </summary>
	class Template implements IItem
	{
		private String creationDate;   
		private CustomMetaConnection customMetas;   
		private String id;   
		private String initialPublishDate;   
		private int itemId;   
		private int itemType;   
		private String lastPublishDate;   
		private int namespaceId;   
		private String outputFormat;   
		private int owningPublicationId;   
		private int priority;   
		private int publicationId;   
		private String title;   
		private String updatedDate;   

		 public String getCreationDate()
		 {
			 return creationDate;
		 }
		 public void setCreationDate(String creationDate)
		 {
			 this.creationDate = creationDate;
		 }

		 public CustomMetaConnection getCustomMetas()
		 {
			 return customMetas;
		 }
		 public void setCustomMetas(CustomMetaConnection customMetas)
		 {
			 this.customMetas = customMetas;
		 }

		 public String getId()
		 {
			 return id;
		 }
		 public void setId(String id)
		 {
			 this.id = id;
		 }

		 public String getInitialPublishDate()
		 {
			 return initialPublishDate;
		 }
		 public void setInitialPublishDate(String initialPublishDate)
		 {
			 this.initialPublishDate = initialPublishDate;
		 }

		 public int getItemId()
		 {
			 return itemId;
		 }
		 public void setItemId(int itemId)
		 {
			 this.itemId = itemId;
		 }

		 public int getItemType()
		 {
			 return itemType;
		 }
		 public void setItemType(int itemType)
		 {
			 this.itemType = itemType;
		 }

		 public String getLastPublishDate()
		 {
			 return lastPublishDate;
		 }
		 public void setLastPublishDate(String lastPublishDate)
		 {
			 this.lastPublishDate = lastPublishDate;
		 }

		 public int getNamespaceId()
		 {
			 return namespaceId;
		 }
		 public void setNamespaceId(int namespaceId)
		 {
			 this.namespaceId = namespaceId;
		 }

		 public String getOutputFormat()
		 {
			 return outputFormat;
		 }
		 public void setOutputFormat(String outputFormat)
		 {
			 this.outputFormat = outputFormat;
		 }

		 public int getOwningPublicationId()
		 {
			 return owningPublicationId;
		 }
		 public void setOwningPublicationId(int owningPublicationId)
		 {
			 this.owningPublicationId = owningPublicationId;
		 }

		 public int getPriority()
		 {
			 return priority;
		 }
		 public void setPriority(int priority)
		 {
			 this.priority = priority;
		 }

		 public int getPublicationId()
		 {
			 return publicationId;
		 }
		 public void setPublicationId(int publicationId)
		 {
			 this.publicationId = publicationId;
		 }

		 public String getTitle()
		 {
			 return title;
		 }
		 public void setTitle(String title)
		 {
			 this.title = title;
		 }

		 public String getUpdatedDate()
		 {
			 return updatedDate;
		 }
		 public void setUpdatedDate(String updatedDate)
		 {
			 this.updatedDate = updatedDate;
		 }
	}

	interface IContent
	{
		String id = null;  
		String type = null;  


		String getId();
		void setId(String id);

		String getType();
		void setType(String type);
	}

	/// <summary>
	/// Represents an item with content.
	/// </summary>
	class RawContent
	{
		private String charSet;   
		private String content;   
		private Dictionary data;   
		private String id;   

		 public String getCharSet()
		 {
			 return charSet;
		 }
		 public void setCharSet(String charSet)
		 {
			 this.charSet = charSet;
		 }

		 public String getContent()
		 {
			 return content;
		 }
		 public void setContent(String content)
		 {
			 this.content = content;
		 }

		 public Dictionary getData()
		 {
			 return data;
		 }
		 public void setData(Dictionary data)
		 {
			 this.data = data;
		 }

		 public String getId()
		 {
			 return id;
		 }
		 public void setId(String id)
		 {
			 this.id = id;
		 }
	}

	/// <summary>
	/// Represents a fragment of content.
	/// </summary>
	interface IContentFragment
	{
		IContent content = null;  
		String creationDate = null;  
		CustomMetaConnection customMetas = null;  
		String id = null;  
		String initialPublishDate = null;  
		int itemId = 0;  
		int itemType = 0;  
		String lastPublishDate = null;  
		int namespaceId = 0;  
		int owningPublicationId = 0;  
		int publicationId = 0;  
		String title = null;  
		String updatedDate = null;  


		IContent getContent();
		void setContent(IContent content);

		String getCreationDate();
		void setCreationDate(String creationDate);

		CustomMetaConnection getCustomMetas();
		void setCustomMetas(CustomMetaConnection customMetas);

		String getId();
		void setId(String id);

		String getInitialPublishDate();
		void setInitialPublishDate(String initialPublishDate);

		int getItemId();
		void setItemId(int itemId);

		int getItemType();
		void setItemType(int itemType);

		String getLastPublishDate();
		void setLastPublishDate(String lastPublishDate);

		int getNamespaceId();
		void setNamespaceId(int namespaceId);

		int getOwningPublicationId();
		void setOwningPublicationId(int owningPublicationId);

		int getPublicationId();
		void setPublicationId(int publicationId);

		String getTitle();
		void setTitle(String title);

		String getUpdatedDate();
		void setUpdatedDate(String updatedDate);
	}

	/// <summary>
	/// A connection to a list of items.
	/// </summary>
	class ItemConnection
	{
		private List<ItemEdge> edges;   

		 public List<ItemEdge> getEdges()
		 {
			 return edges;
		 }
		 public void setEdges(List<ItemEdge> edges)
		 {
			 this.edges = edges;
		 }
	}

	/// <summary>
	/// An edge in a connection
	/// </summary>
	class ItemEdge
	{
		private IItem node;   
		private String cursor;   

		 public IItem getNode()
		 {
			 return node;
		 }
		 public void setNode(IItem node)
		 {
			 this.node = node;
		 }

		 public String getCursor()
		 {
			 return cursor;
		 }
		 public void setCursor(String cursor)
		 {
			 this.cursor = cursor;
		 }
	}

	/// <summary>
	/// Item filter
	/// </summary>
	class InputItemFilter
	{
		private List<InputItemFilter> and;   
		private InputCustomMetaCriteria customMeta;   
		private List<ItemType> itemTypes;   
		private InputKeywordCriteria keyword;   
		private List<Integer> namespaceIds;   
		private List<InputItemFilter> or;   
		private List<Integer> publicationIds;   

		 public List<InputItemFilter> getAnd()
		 {
			 return and;
		 }
		 public void setAnd(List<InputItemFilter> and)
		 {
			 this.and = and;
		 }

		 public InputCustomMetaCriteria getCustomMeta()
		 {
			 return customMeta;
		 }
		 public void setCustomMeta(InputCustomMetaCriteria customMeta)
		 {
			 this.customMeta = customMeta;
		 }

		 public List<ItemType> getItemTypes()
		 {
			 return itemTypes;
		 }
		 public void setItemTypes(List<ItemType> itemTypes)
		 {
			 this.itemTypes = itemTypes;
		 }

		 public InputKeywordCriteria getKeyword()
		 {
			 return keyword;
		 }
		 public void setKeyword(InputKeywordCriteria keyword)
		 {
			 this.keyword = keyword;
		 }

		 public List<Integer> getNamespaceIds()
		 {
			 return namespaceIds;
		 }
		 public void setNamespaceIds(List<Integer> namespaceIds)
		 {
			 this.namespaceIds = namespaceIds;
		 }

		 public List<InputItemFilter> getOr()
		 {
			 return or;
		 }
		 public void setOr(List<InputItemFilter> or)
		 {
			 this.or = or;
		 }

		 public List<Integer> getPublicationIds()
		 {
			 return publicationIds;
		 }
		 public void setPublicationIds(List<Integer> publicationIds)
		 {
			 this.publicationIds = publicationIds;
		 }
	}

	/// <summary>
	/// Criteria for Custom Meta
	/// </summary>
	class InputCustomMetaCriteria
	{
		private String key;   
		private CriteriaScope scope;   
		private String value;   
		private CustomMetaValueType valueType;   

		 public String getKey()
		 {
			 return key;
		 }
		 public void setKey(String key)
		 {
			 this.key = key;
		 }

		 public CriteriaScope getScope()
		 {
			 return scope;
		 }
		 public void setScope(CriteriaScope scope)
		 {
			 this.scope = scope;
		 }

		 public String getValue()
		 {
			 return value;
		 }
		 public void setValue(String value)
		 {
			 this.value = value;
		 }

		 public CustomMetaValueType getValueType()
		 {
			 return valueType;
		 }
		 public void setValueType(CustomMetaValueType valueType)
		 {
			 this.valueType = valueType;
		 }
	}

	/*[JsonConverter(typeof(StringEnumConverter))]*/
	enum CriteriaScope
	{
		/// <summary>
		/// Publication
		/// </summary>
		Publication,

		/// <summary>
		/// Item
		/// </summary>
		Item,

		ItemInPublication
	}

	/*[JsonConverter(typeof(StringEnumConverter))]*/
	enum ItemType
	{
		/// <summary>
		/// PUBLICATION
		/// </summary>
		PUBLICATION,

		/// <summary>
		/// STRUCTURE_GROUP
		/// </summary>
		STRUCTURE_GROUP,

		/// <summary>
		/// COMPONENT
		/// </summary>
		COMPONENT,

		/// <summary>
		/// COMPONENT_TEMPLATE
		/// </summary>
		COMPONENT_TEMPLATE,

		/// <summary>
		/// PAGE
		/// </summary>
		PAGE,

		/// <summary>
		/// PAGE_TEMPLATE
		/// </summary>
		PAGE_TEMPLATE,

		/// <summary>
		/// CATEGORY
		/// </summary>
		CATEGORY,

		/// <summary>
		/// KEYWORD
		/// </summary>
		KEYWORD,

		COMPONENT_PRESENTATION
	}

	class InputKeywordCriteria
	{
		private int categoryId;   
		private String categoryName;   
		private String key;   
		private int keywordId;   

		 public int getCategoryId()
		 {
			 return categoryId;
		 }
		 public void setCategoryId(int categoryId)
		 {
			 this.categoryId = categoryId;
		 }

		 public String getCategoryName()
		 {
			 return categoryName;
		 }
		 public void setCategoryName(String categoryName)
		 {
			 this.categoryName = categoryName;
		 }

		 public String getKey()
		 {
			 return key;
		 }
		 public void setKey(String key)
		 {
			 this.key = key;
		 }

		 public int getKeywordId()
		 {
			 return keywordId;
		 }
		 public void setKeywordId(int keywordId)
		 {
			 this.keywordId = keywordId;
		 }
	}

	/// <summary>
	/// Represents a page.
	/// </summary>
	class Page implements IContainer, IItem
	{
		private List<IItem> containerItems;   
		private IContent content;   
		private String creationDate;   
		private CustomMetaConnection customMetas;   
		private String fileName;   
		private String id;   
		private String initialPublishDate;   
		private int itemId;   
		private int itemType;   
		private String lastPublishDate;   
		private int namespaceId;   
		private int owningPublicationId;   
		private Template pageTemplate;   
		private int publicationId;   
		private RawContent rawContent;   
		private List<ITaxonomyItem> taxonomies;   
		private String title;   
		private String updatedDate;   
		private String url;   

		 public List<IItem> getContainerItems()
		 {
			 return containerItems;
		 }
		 public void setContainerItems(List<IItem> containerItems)
		 {
			 this.containerItems = containerItems;
		 }

		 public IContent getContent()
		 {
			 return content;
		 }
		 public void setContent(IContent content)
		 {
			 this.content = content;
		 }

		 public String getCreationDate()
		 {
			 return creationDate;
		 }
		 public void setCreationDate(String creationDate)
		 {
			 this.creationDate = creationDate;
		 }

		 public CustomMetaConnection getCustomMetas()
		 {
			 return customMetas;
		 }
		 public void setCustomMetas(CustomMetaConnection customMetas)
		 {
			 this.customMetas = customMetas;
		 }

		 public String getFileName()
		 {
			 return fileName;
		 }
		 public void setFileName(String fileName)
		 {
			 this.fileName = fileName;
		 }

		 public String getId()
		 {
			 return id;
		 }
		 public void setId(String id)
		 {
			 this.id = id;
		 }

		 public String getInitialPublishDate()
		 {
			 return initialPublishDate;
		 }
		 public void setInitialPublishDate(String initialPublishDate)
		 {
			 this.initialPublishDate = initialPublishDate;
		 }

		 public int getItemId()
		 {
			 return itemId;
		 }
		 public void setItemId(int itemId)
		 {
			 this.itemId = itemId;
		 }

		 public int getItemType()
		 {
			 return itemType;
		 }
		 public void setItemType(int itemType)
		 {
			 this.itemType = itemType;
		 }

		 public String getLastPublishDate()
		 {
			 return lastPublishDate;
		 }
		 public void setLastPublishDate(String lastPublishDate)
		 {
			 this.lastPublishDate = lastPublishDate;
		 }

		 public int getNamespaceId()
		 {
			 return namespaceId;
		 }
		 public void setNamespaceId(int namespaceId)
		 {
			 this.namespaceId = namespaceId;
		 }

		 public int getOwningPublicationId()
		 {
			 return owningPublicationId;
		 }
		 public void setOwningPublicationId(int owningPublicationId)
		 {
			 this.owningPublicationId = owningPublicationId;
		 }

		 public Template getPageTemplate()
		 {
			 return pageTemplate;
		 }
		 public void setPageTemplate(Template pageTemplate)
		 {
			 this.pageTemplate = pageTemplate;
		 }

		 public int getPublicationId()
		 {
			 return publicationId;
		 }
		 public void setPublicationId(int publicationId)
		 {
			 this.publicationId = publicationId;
		 }

		 public RawContent getRawContent()
		 {
			 return rawContent;
		 }
		 public void setRawContent(RawContent rawContent)
		 {
			 this.rawContent = rawContent;
		 }

		 public List<ITaxonomyItem> getTaxonomies()
		 {
			 return taxonomies;
		 }
		 public void setTaxonomies(List<ITaxonomyItem> taxonomies)
		 {
			 this.taxonomies = taxonomies;
		 }

		 public String getTitle()
		 {
			 return title;
		 }
		 public void setTitle(String title)
		 {
			 this.title = title;
		 }

		 public String getUpdatedDate()
		 {
			 return updatedDate;
		 }
		 public void setUpdatedDate(String updatedDate)
		 {
			 this.updatedDate = updatedDate;
		 }

		 public String getUrl()
		 {
			 return url;
		 }
		 public void setUrl(String url)
		 {
			 this.url = url;
		 }
	}

	/// <summary>
	/// Represents the type of container.
	/// </summary>
	/*[JsonConverter(typeof(StringEnumConverter))]*/
	enum ContainerType
	{
		COMPONENT_PRESENTATION
	}

	/// <summary>
	/// Represents a container for items.
	/// </summary>
	interface IContainer
	{
		List<IItem> containerItems = null;  


		List<IItem> getContainerItems();
		void setContainerItems(List<IItem> containerItems);
	}

	/// <summary>
	/// Represents a related set of entities.
	/// </summary>
	interface ITaggable
	{
		List<ITaxonomyItem> taxonomies = null;  


		List<ITaxonomyItem> getTaxonomies();
		void setTaxonomies(List<ITaxonomyItem> taxonomies);
	}

	/// <summary>
	/// A connection to a list of items.
	/// </summary>
	class PageConnection
	{
		private List<PageEdge> edges;   

		 public List<PageEdge> getEdges()
		 {
			 return edges;
		 }
		 public void setEdges(List<PageEdge> edges)
		 {
			 this.edges = edges;
		 }
	}

	/// <summary>
	/// An edge in a connection
	/// </summary>
	class PageEdge
	{
		private Page node;   
		private String cursor;   

		 public Page getNode()
		 {
			 return node;
		 }
		 public void setNode(Page node)
		 {
			 this.node = node;
		 }

		 public String getCursor()
		 {
			 return cursor;
		 }
		 public void setCursor(String cursor)
		 {
			 this.cursor = cursor;
		 }
	}

	/// <summary>
	/// Represents a publication.
	/// </summary>
	class Publication implements IItem
	{
		private String creationDate;   
		private CustomMetaConnection customMetas;   
		private String id;   
		private String initialPublishDate;   
		private int itemId;   
		private int itemType;   
		private String lastPublishDate;   
		private String multimediaPath;   
		private String multimediaUrl;   
		private int namespaceId;   
		private int owningPublicationId;   
		private int publicationId;   
		private String publicationKey;   
		private String publicationPath;   
		private String publicationUrl;   
		private String title;   
		private String updatedDate;   

		 public String getCreationDate()
		 {
			 return creationDate;
		 }
		 public void setCreationDate(String creationDate)
		 {
			 this.creationDate = creationDate;
		 }

		 public CustomMetaConnection getCustomMetas()
		 {
			 return customMetas;
		 }
		 public void setCustomMetas(CustomMetaConnection customMetas)
		 {
			 this.customMetas = customMetas;
		 }

		 public String getId()
		 {
			 return id;
		 }
		 public void setId(String id)
		 {
			 this.id = id;
		 }

		 public String getInitialPublishDate()
		 {
			 return initialPublishDate;
		 }
		 public void setInitialPublishDate(String initialPublishDate)
		 {
			 this.initialPublishDate = initialPublishDate;
		 }

		 public int getItemId()
		 {
			 return itemId;
		 }
		 public void setItemId(int itemId)
		 {
			 this.itemId = itemId;
		 }

		 public int getItemType()
		 {
			 return itemType;
		 }
		 public void setItemType(int itemType)
		 {
			 this.itemType = itemType;
		 }

		 public String getLastPublishDate()
		 {
			 return lastPublishDate;
		 }
		 public void setLastPublishDate(String lastPublishDate)
		 {
			 this.lastPublishDate = lastPublishDate;
		 }

		 public String getMultimediaPath()
		 {
			 return multimediaPath;
		 }
		 public void setMultimediaPath(String multimediaPath)
		 {
			 this.multimediaPath = multimediaPath;
		 }

		 public String getMultimediaUrl()
		 {
			 return multimediaUrl;
		 }
		 public void setMultimediaUrl(String multimediaUrl)
		 {
			 this.multimediaUrl = multimediaUrl;
		 }

		 public int getNamespaceId()
		 {
			 return namespaceId;
		 }
		 public void setNamespaceId(int namespaceId)
		 {
			 this.namespaceId = namespaceId;
		 }

		 public int getOwningPublicationId()
		 {
			 return owningPublicationId;
		 }
		 public void setOwningPublicationId(int owningPublicationId)
		 {
			 this.owningPublicationId = owningPublicationId;
		 }

		 public int getPublicationId()
		 {
			 return publicationId;
		 }
		 public void setPublicationId(int publicationId)
		 {
			 this.publicationId = publicationId;
		 }

		 public String getPublicationKey()
		 {
			 return publicationKey;
		 }
		 public void setPublicationKey(String publicationKey)
		 {
			 this.publicationKey = publicationKey;
		 }

		 public String getPublicationPath()
		 {
			 return publicationPath;
		 }
		 public void setPublicationPath(String publicationPath)
		 {
			 this.publicationPath = publicationPath;
		 }

		 public String getPublicationUrl()
		 {
			 return publicationUrl;
		 }
		 public void setPublicationUrl(String publicationUrl)
		 {
			 this.publicationUrl = publicationUrl;
		 }

		 public String getTitle()
		 {
			 return title;
		 }
		 public void setTitle(String title)
		 {
			 this.title = title;
		 }

		 public String getUpdatedDate()
		 {
			 return updatedDate;
		 }
		 public void setUpdatedDate(String updatedDate)
		 {
			 this.updatedDate = updatedDate;
		 }
	}

	/// <summary>
	/// A connection to a list of items.
	/// </summary>
	class PublicationConnection
	{
		private List<PublicationEdge> edges;   

		 public List<PublicationEdge> getEdges()
		 {
			 return edges;
		 }
		 public void setEdges(List<PublicationEdge> edges)
		 {
			 this.edges = edges;
		 }
	}

	/// <summary>
	/// An edge in a connection
	/// </summary>
	class PublicationEdge
	{
		private Publication node;   
		private String cursor;   

		 public Publication getNode()
		 {
			 return node;
		 }
		 public void setNode(Publication node)
		 {
			 this.node = node;
		 }

		 public String getCursor()
		 {
			 return cursor;
		 }
		 public void setCursor(String cursor)
		 {
			 this.cursor = cursor;
		 }
	}

	/// <summary>
	/// Represents a filter for a publication query.
	/// </summary>
	class InputPublicationFilter
	{
		private ContentFilterQueryType queryType;   
		private String value;   
		private CustomMetaValueType valueType;   

		 public ContentFilterQueryType getQueryType()
		 {
			 return queryType;
		 }
		 public void setQueryType(ContentFilterQueryType queryType)
		 {
			 this.queryType = queryType;
		 }

		 public String getValue()
		 {
			 return value;
		 }
		 public void setValue(String value)
		 {
			 this.value = value;
		 }

		 public CustomMetaValueType getValueType()
		 {
			 return valueType;
		 }
		 public void setValueType(CustomMetaValueType valueType)
		 {
			 this.valueType = valueType;
		 }
	}

	/*[JsonConverter(typeof(StringEnumConverter))]*/
	enum ContentFilterQueryType
	{
		CUSTOM_META
	}

	/// <summary>
	/// Represents a structure group.
	/// </summary>
	class StructureGroup implements IItem
	{
		private TaxonomyItemConnection children;   
		private String creationDate;   
		private CustomMetaConnection customMetas;   
		private int depth;   
		private String directory;   
		private String id;   
		private String initialPublishDate;   
		private int itemId;   
		private int itemType;   
		private String key;   
		private String lastPublishDate;   
		private int namespaceId;   
		private int owningPublicationId;   
		private ITaxonomyItem parent;   
		private int publicationId;   
		private int taxonomyId;   
		private TaxonomyType taxonomyType;   
		private String title;   
		private String updatedDate;   
		private boolean hasChildren;   
		private boolean Abstract;   
		private boolean navigable;   

		 public TaxonomyItemConnection getChildren()
		 {
			 return children;
		 }
		 public void setChildren(TaxonomyItemConnection children)
		 {
			 this.children = children;
		 }

		 public String getCreationDate()
		 {
			 return creationDate;
		 }
		 public void setCreationDate(String creationDate)
		 {
			 this.creationDate = creationDate;
		 }

		 public CustomMetaConnection getCustomMetas()
		 {
			 return customMetas;
		 }
		 public void setCustomMetas(CustomMetaConnection customMetas)
		 {
			 this.customMetas = customMetas;
		 }

		 public int getDepth()
		 {
			 return depth;
		 }
		 public void setDepth(int depth)
		 {
			 this.depth = depth;
		 }

		 public String getDirectory()
		 {
			 return directory;
		 }
		 public void setDirectory(String directory)
		 {
			 this.directory = directory;
		 }

		 public String getId()
		 {
			 return id;
		 }
		 public void setId(String id)
		 {
			 this.id = id;
		 }

		 public String getInitialPublishDate()
		 {
			 return initialPublishDate;
		 }
		 public void setInitialPublishDate(String initialPublishDate)
		 {
			 this.initialPublishDate = initialPublishDate;
		 }

		 public int getItemId()
		 {
			 return itemId;
		 }
		 public void setItemId(int itemId)
		 {
			 this.itemId = itemId;
		 }

		 public int getItemType()
		 {
			 return itemType;
		 }
		 public void setItemType(int itemType)
		 {
			 this.itemType = itemType;
		 }

		 public String getKey()
		 {
			 return key;
		 }
		 public void setKey(String key)
		 {
			 this.key = key;
		 }

		 public String getLastPublishDate()
		 {
			 return lastPublishDate;
		 }
		 public void setLastPublishDate(String lastPublishDate)
		 {
			 this.lastPublishDate = lastPublishDate;
		 }

		 public int getNamespaceId()
		 {
			 return namespaceId;
		 }
		 public void setNamespaceId(int namespaceId)
		 {
			 this.namespaceId = namespaceId;
		 }

		 public int getOwningPublicationId()
		 {
			 return owningPublicationId;
		 }
		 public void setOwningPublicationId(int owningPublicationId)
		 {
			 this.owningPublicationId = owningPublicationId;
		 }

		 public ITaxonomyItem getParent()
		 {
			 return parent;
		 }
		 public void setParent(ITaxonomyItem parent)
		 {
			 this.parent = parent;
		 }

		 public int getPublicationId()
		 {
			 return publicationId;
		 }
		 public void setPublicationId(int publicationId)
		 {
			 this.publicationId = publicationId;
		 }

		 public int getTaxonomyId()
		 {
			 return taxonomyId;
		 }
		 public void setTaxonomyId(int taxonomyId)
		 {
			 this.taxonomyId = taxonomyId;
		 }

		 public TaxonomyType getTaxonomyType()
		 {
			 return taxonomyType;
		 }
		 public void setTaxonomyType(TaxonomyType taxonomyType)
		 {
			 this.taxonomyType = taxonomyType;
		 }

		 public String getTitle()
		 {
			 return title;
		 }
		 public void setTitle(String title)
		 {
			 this.title = title;
		 }

		 public String getUpdatedDate()
		 {
			 return updatedDate;
		 }
		 public void setUpdatedDate(String updatedDate)
		 {
			 this.updatedDate = updatedDate;
		 }

		 public boolean isHasChildren()
		 {
			 return hasChildren;
		 }
		 public void setHasChildren(boolean hasChildren)
		 {
			 this.hasChildren = hasChildren;
		 }

		 public boolean isAbstract()
		 {
			 return Abstract;
		 }
		 public void setAbstract(boolean anAbstract)
		 {
			 this.Abstract = anAbstract;
		 }

		 public boolean isNavigable()
		 {
			 return navigable;
		 }
		 public void setNavigable(boolean navigable)
		 {
			 this.navigable = navigable;
		 }
	}

	/// <summary>
	/// A connection to a list of items.
	/// </summary>
	class StructureGroupConnection
	{
		private List<StructureGroupEdge> edges;   

		 public List<StructureGroupEdge> getEdges()
		 {
			 return edges;
		 }
		 public void setEdges(List<StructureGroupEdge> edges)
		 {
			 this.edges = edges;
		 }
	}

	/// <summary>
	/// An edge in a connection
	/// </summary>
	class StructureGroupEdge
	{
		private StructureGroup node;   
		private String cursor;   

		 public StructureGroup getNode()
		 {
			 return node;
		 }
		 public void setNode(StructureGroup node)
		 {
			 this.node = node;
		 }

		 public String getCursor()
		 {
			 return cursor;
		 }
		 public void setCursor(String cursor)
		 {
			 this.cursor = cursor;
		 }
	}

	class TaxonomySitemapItem implements ISitemapItem
	{
		private int classifiedItemsCount;   
		private String description;   
		private String id;   
		private List<ISitemapItem> items;   
		private String key;   
		private String originalTitle;   
		private String publishedDate;   
		private String title;   
		private String type;   
		private String url;   
		private boolean Abstract;   
		private boolean hasChildNodes;   
		private boolean visible;   

		 public int getClassifiedItemsCount()
		 {
			 return classifiedItemsCount;
		 }
		 public void setClassifiedItemsCount(int classifiedItemsCount)
		 {
			 this.classifiedItemsCount = classifiedItemsCount;
		 }

		 public String getDescription()
		 {
			 return description;
		 }
		 public void setDescription(String description)
		 {
			 this.description = description;
		 }

		 public String getId()
		 {
			 return id;
		 }
		 public void setId(String id)
		 {
			 this.id = id;
		 }

		 public List<ISitemapItem> getItems()
		 {
			 return items;
		 }
		 public void setItems(List<ISitemapItem> items)
		 {
			 this.items = items;
		 }

		 public String getKey()
		 {
			 return key;
		 }
		 public void setKey(String key)
		 {
			 this.key = key;
		 }

		 public String getOriginalTitle()
		 {
			 return originalTitle;
		 }
		 public void setOriginalTitle(String originalTitle)
		 {
			 this.originalTitle = originalTitle;
		 }

		 public String getPublishedDate()
		 {
			 return publishedDate;
		 }
		 public void setPublishedDate(String publishedDate)
		 {
			 this.publishedDate = publishedDate;
		 }

		 public String getTitle()
		 {
			 return title;
		 }
		 public void setTitle(String title)
		 {
			 this.title = title;
		 }

		 public String getType()
		 {
			 return type;
		 }
		 public void setType(String type)
		 {
			 this.type = type;
		 }

		 public String getUrl()
		 {
			 return url;
		 }
		 public void setUrl(String url)
		 {
			 this.url = url;
		 }

		 public boolean isAbstract()
		 {
			 return Abstract;
		 }
		 public void setAbstract(boolean anAbstract)
		 {
			 this.Abstract = anAbstract;
		 }

		 public boolean isHasChildNodes()
		 {
			 return hasChildNodes;
		 }
		 public void setHasChildNodes(boolean hasChildNodes)
		 {
			 this.hasChildNodes = hasChildNodes;
		 }

		 public boolean isVisible()
		 {
			 return visible;
		 }
		 public void setVisible(boolean visible)
		 {
			 this.visible = visible;
		 }
	}

	/// <summary>
	/// Sitemap Item
	/// </summary>
	interface ISitemapItem
	{
		String id = null;  
		String originalTitle = null;  
		String publishedDate = null;  
		String title = null;  
		String type = null;  
		String url = null;  
		boolean visible = false;  


		String getId();
		void setId(String id);

		String getOriginalTitle();
		void setOriginalTitle(String originalTitle);

		String getPublishedDate();
		void setPublishedDate(String publishedDate);

		String getTitle();
		void setTitle(String title);

		String getType();
		void setType(String type);

		String getUrl();
		void setUrl(String url);

		boolean isVisible();
		void setVisible(boolean visible);
	}

	/// <summary>
	/// Represents a regular component.
	/// </summary>
	class Component implements IItem
	{
		private String creationDate;   
		private CustomMetaConnection customMetas;   
		private String id;   
		private String initialPublishDate;   
		private int itemId;   
		private int itemType;   
		private String lastPublishDate;   
		private int namespaceId;   
		private int owningPublicationId;   
		private int publicationId;   
		private int schemaId;   
		private List<ITaxonomyItem> taxonomies;   
		private String title;   
		private String updatedDate;   
		private boolean multiMedia;   

		 public String getCreationDate()
		 {
			 return creationDate;
		 }
		 public void setCreationDate(String creationDate)
		 {
			 this.creationDate = creationDate;
		 }

		 public CustomMetaConnection getCustomMetas()
		 {
			 return customMetas;
		 }
		 public void setCustomMetas(CustomMetaConnection customMetas)
		 {
			 this.customMetas = customMetas;
		 }

		 public String getId()
		 {
			 return id;
		 }
		 public void setId(String id)
		 {
			 this.id = id;
		 }

		 public String getInitialPublishDate()
		 {
			 return initialPublishDate;
		 }
		 public void setInitialPublishDate(String initialPublishDate)
		 {
			 this.initialPublishDate = initialPublishDate;
		 }

		 public int getItemId()
		 {
			 return itemId;
		 }
		 public void setItemId(int itemId)
		 {
			 this.itemId = itemId;
		 }

		 public int getItemType()
		 {
			 return itemType;
		 }
		 public void setItemType(int itemType)
		 {
			 this.itemType = itemType;
		 }

		 public String getLastPublishDate()
		 {
			 return lastPublishDate;
		 }
		 public void setLastPublishDate(String lastPublishDate)
		 {
			 this.lastPublishDate = lastPublishDate;
		 }

		 public int getNamespaceId()
		 {
			 return namespaceId;
		 }
		 public void setNamespaceId(int namespaceId)
		 {
			 this.namespaceId = namespaceId;
		 }

		 public int getOwningPublicationId()
		 {
			 return owningPublicationId;
		 }
		 public void setOwningPublicationId(int owningPublicationId)
		 {
			 this.owningPublicationId = owningPublicationId;
		 }

		 public int getPublicationId()
		 {
			 return publicationId;
		 }
		 public void setPublicationId(int publicationId)
		 {
			 this.publicationId = publicationId;
		 }

		 public int getSchemaId()
		 {
			 return schemaId;
		 }
		 public void setSchemaId(int schemaId)
		 {
			 this.schemaId = schemaId;
		 }

		 public List<ITaxonomyItem> getTaxonomies()
		 {
			 return taxonomies;
		 }
		 public void setTaxonomies(List<ITaxonomyItem> taxonomies)
		 {
			 this.taxonomies = taxonomies;
		 }

		 public String getTitle()
		 {
			 return title;
		 }
		 public void setTitle(String title)
		 {
			 this.title = title;
		 }

		 public String getUpdatedDate()
		 {
			 return updatedDate;
		 }
		 public void setUpdatedDate(String updatedDate)
		 {
			 this.updatedDate = updatedDate;
		 }

		 public boolean isMultiMedia()
		 {
			 return multiMedia;
		 }
		 public void setMultiMedia(boolean multiMedia)
		 {
			 this.multiMedia = multiMedia;
		 }
	}

	/// <summary>
	/// Untyped content where all data is available in a Map structure.
	/// </summary>
	class UntypedContent implements IContent
	{
		private Dictionary data;   
		private String id;   
		private String type;   

		 public Dictionary getData()
		 {
			 return data;
		 }
		 public void setData(Dictionary data)
		 {
			 this.data = data;
		 }

		 public String getId()
		 {
			 return id;
		 }
		 public void setId(String id)
		 {
			 this.id = id;
		 }

		 public String getType()
		 {
			 return type;
		 }
		 public void setType(String type)
		 {
			 this.type = type;
		 }
	}

	/// <summary>
	/// Represents an Ambient Data Framework claim value.
	/// </summary>
	class ClaimValue
	{
		private ClaimValueType type;   
		private String uri;   
		private String value;   

		 public ClaimValueType getType()
		 {
			 return type;
		 }
		 public void setType(ClaimValueType type)
		 {
			 this.type = type;
		 }

		 public String getUri()
		 {
			 return uri;
		 }
		 public void setUri(String uri)
		 {
			 this.uri = uri;
		 }

		 public String getValue()
		 {
			 return value;
		 }
		 public void setValue(String value)
		 {
			 this.value = value;
		 }
	}

	class PageSitemapItem implements ISitemapItem
	{
		private String id;   
		private String originalTitle;   
		private String publishedDate;   
		private String title;   
		private String type;   
		private String url;   
		private boolean visible;   

		 public String getId()
		 {
			 return id;
		 }
		 public void setId(String id)
		 {
			 this.id = id;
		 }

		 public String getOriginalTitle()
		 {
			 return originalTitle;
		 }
		 public void setOriginalTitle(String originalTitle)
		 {
			 this.originalTitle = originalTitle;
		 }

		 public String getPublishedDate()
		 {
			 return publishedDate;
		 }
		 public void setPublishedDate(String publishedDate)
		 {
			 this.publishedDate = publishedDate;
		 }

		 public String getTitle()
		 {
			 return title;
		 }
		 public void setTitle(String title)
		 {
			 this.title = title;
		 }

		 public String getType()
		 {
			 return type;
		 }
		 public void setType(String type)
		 {
			 this.type = type;
		 }

		 public String getUrl()
		 {
			 return url;
		 }
		 public void setUrl(String url)
		 {
			 this.url = url;
		 }

		 public boolean isVisible()
		 {
			 return visible;
		 }
		 public void setVisible(boolean visible)
		 {
			 this.visible = visible;
		 }
	}

	/// <summary>
	/// Represents a node.
	/// </summary>
	class Node
	{
		private String id;   

		 public String getId()
		 {
			 return id;
		 }
		 public void setId(String id)
		 {
			 this.id = id;
		 }
	}

