name: Build

on:
  push:
    branches: [ develop, release/2.2 ]
  pull_request:
    branches: [ develop, release/2.2 ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Restore NuGet Packages
      run: nuget restore net/sln/Sdl.Tridion.Api.Client.sln
    - name: Build and Publish Web App
      run: msbuild net/sln/Sdl.Tridion.Api.Client.sln /p:Configuration=Release
      